# Auto Label Git Config
# 'label_name'
# -path_of_diff/where/code_lives/to_base_label upon

# Any changes to any file in the .github/workflow directory
'Github Actions':
  - .github/workflows/*

# Any changes to any file in the dockerfiles and docker-compose.yml
'Docker':
  - '**/Dockerfile'
  - docker-compose.yml

# Any changes to any file or subdirectories in the Frontend directory
'Frontend':
  - /frontend/**/*

# Any changes to any file or subdirectories in the Backend directory
'Backend':
  - /backend/**/*

# Any changes to any environment variables
'Environment Variables':
  - '/**/*.env*/'

# Any changes to any swagger documents
'Swagger':
  - /backend/src/docs/*.yml

# Any changes to any swagger configurations
'Swagger Configurations':
  -/backend/src/config/*.ts
