apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: APP
    description: Application name
    value: nr-sustainment-capstone-2024
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: ORG
    description: Organization name; e.g. bcgov or bcdevops
    value: bcgov
  - name: TAG
    description: Image
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP}-${TAG}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 5173
          protocol: TCP
          name: http-5173
      selector:
        service: ${APP}-${TAG}-${COMPONENT}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${APP}-${TAG}
        deployment: ${APP}-${TAG}-${COMPONENT}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      strategy:
        type: RollingUpdate
      selector:
        matchLabels:
          deployment: ${APP}-${TAG}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${APP}-${TAG}
            deployment: ${APP}-${TAG}-${COMPONENT}
            service: ${APP}-${TAG}-${COMPONENT}
        spec:
          containers:
            - name: ${APP}-${TAG}-${COMPONENT}
              image: "ghcr.io/${ORG}/${APP}/${COMPONENT}:${TAG}"
              securityContext:
                runAsUser: 1011540000
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: VITE_BACKEND_URL
                  value: http://${APP}-${TAG}-backend/api
              ports:
                - name: http
                  containerPort: 5173
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                timeoutSeconds: 10
                successThreshold: 3
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
              resources: # this is optional
                limits:
                  cpu: 150m
                  memory: 150Mi
                requests:
                  cpu: 50m
                  memory: 75Mi
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP}-${TAG}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      host: ${APP}-${TAG}-${COMPONENT}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: http-5173
      to:
        kind: Service
        name: ${APP}-${TAG}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
