# Reusable vars
x-var:
  - &POSTGRES_USER
    postgres

# Postgres envars
x-postgres-vars: &postgres-vars
  POSTGRES_DATABASE: postgres
  POSTGRES_HOST: quackStack-db
  POSTGRES_PASSWORD: default
  POSTGRES_USER: *POSTGRES_USER

name: quackstack-bb
services:
  # DB
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: quackStack-db
    environment:
      <<: *postgres-vars
    ports: [5432:5432]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]

  # PGAdmin
  pgadmin:
    container_name: quackStack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qs.com
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports: [5050:80]
    profiles: ["pgadmin"]

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run ${CMD:-dev}
    container_name: quackStack-api
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: app
          ignore: [node_modules]
    environment:
      <<: *postgres-vars
    healthcheck:
      test: curl localhost:3000/api/health | grep 'NMP API is healthy and ready!'
    ports: [3000:3000]

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run ${CMD:-dev}
    container_name: quackStack-frontend
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore: [node_modules]
    environment:
      VITE_BACKEND_URL: http://localhost:3000/api
    healthcheck:
      test: curl --fail http://localhost:5173 || exit 1
    ports: [5173:5173]
