version: "3.9"
name: quackstack-nmp
services:
  ##########################################################
  #                      FrontEnd                          #
  ##########################################################
  frontend:
    container_name: quackStack-frontend
    build:
    context: ./
    dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .github/
    ports:
      - ${PORT:-8080}:8080
    healthcheck:
      test: curl--fail http://localhost:8080 || exit 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 30s

  ##########################################################
  #                      DB                                #
  ##########################################################
  database:
    image: postgres:15
    container_name: quackStack-db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-admin}
      - POSTGRES_USER${POSTGRES_USER:-USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-nmp}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD","pg_isready","-U","${POSTGRES_USER:-user}"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s

  ##########################################################
  #                      PGAdmin                           #
  ##########################################################
  pgadmin:
    image: dpage/pgadmin4
    container_name: quackStack-pgadmin
    ports:
      - 5050:80
    environment:
       PGADMIN_DEFAULT_PASSWORD: admin
       PGADMIN_DEFAULT_EMAIL: admin@qs.com
    networks:
    - quackStack-network
##########################################################
#                      Network                           #
##########################################################
networks:
  quackStack-network:
    driver: "bridge"
