name: quackstack-nmp
services:

  ##########################################################
  #                      DB                                #
  ##########################################################
  database:
    image: postgres:15
    container_name: quackStack-db
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/db/entrypoint:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    networks:
      - quackStack-network

  ####################
  #     PGAdmin      #
  ####################
  pgadmin:
    image: dpage/pgadmin4
    container_name: quackStack-pgadmin
    ports:
      - 5050:80
    env_file:
      - ./.env
    networks:
      - quackStack-network

  ###################
  #   Backend      #
  ###################
  backend:
    container_name: quackStack-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /backend/src
          ignore:
            - node_modules
    healthcheck:
      test: curl localhost:${PORT:-3000}/api/health | grep 'NMP API is healthy and ready!'
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      database:
        condition: service_healthy

  ##########################################################
  #                      FrontEnd                          #
  ##########################################################
  frontend:
    container_name: quackStack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run serve
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          ignore:
            - node_modules
    ports:
      - ${PORT:-5173}:5173
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5173 || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      backend:
        condition: service_healthy

###################
#   Networks      #
###################
networks:
  quackStack-network:
    driver: "bridge"
volumes:
  postgres:
    name: quackStack-db-vol-postgres
