version: "3.9"
name: quackstack-nmp
services:
  ##########################################################
  #                      FrontEnd                          #
  ##########################################################
  frontend:
    container_name: quackStack-frontend
    build:
    context: ./
    dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .github/
    ports:
      - ${PORT:-8080}:8080
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 30s
      depends_on:
        backend:
          condition: service_healthy
  ##########################################################
  #                      BackEnd                           #
  ##########################################################
  backend:
    container_name: quackStack-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - API_PORT=${API_PORT:-3000}
      - API_HOSTNAME=${API_HOSTNAME:-localhost}
      - POSTGRES_USER=${POSTGRES_USER:-USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-nmp}
      - POSTGRES_HOST=${POSTGRES_HOST:-admin}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - CONTAINERIZED=true
    networks:
      - quackStack-network
    ports:
      - ${PORT:-3000}:3000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
      depends_on:
        database:
          condition: service_healthy

  ##########################################################
  #                      DB                                #
  ##########################################################
  database:
    image: postgres:15
    container_name: quackStack-db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-admin}
      - POSTGRES_USER${POSTGRES_USER:-USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-nmp}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD","pg_isready","-U","${POSTGRES_USER:-user}"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s

  ##########################################################
  #                      PGAdmin                           #
  ##########################################################
  pgadmin:
    image: dpage/pgadmin4
    container_name: quackStack-pgadmin
    ports:
      - 5050:80
    environment:
       PGADMIN_DEFAULT_PASSWORD: admin
       PGADMIN_DEFAULT_EMAIL: admin@qs.com
    networks:
    - quackStack-network
##########################################################
#                      Network                           #
##########################################################
networks:
  quackStack-network:
    driver: "bridge"
