version: "3.9"
name: quackstack-nmp
services:
  ###################
  #     DB          #
  ###################
  database:
    image: postgres:15
    container_name: quackStack-db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-admin}
      - POSTGRES_USER${POSTGRES_USER:-USER}
      - POSTGRES_PASSWORD=${POSTGRESS_PASSWORD:-admin}
      - POSTGRES_DATABASE=${POSTGRESS_DATABASE:-nmp}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD","pg_isready","-U","${POSTGRES_USER:-user}"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
  ####################
  #     PGAdmin      #
  ####################
  pgadmin:
    image: dpage/pgadmin4
    container_name: quackStack-pgadmin
    ports:
      - 5050:80
    environment:
       PGADMIN_DEFAULT_PASSWORD: admin
       PGADMIN_DEFAULT_EMAIL: admin@nmp.container_name
    networks:
    - quackStack-network
###################
#   Networks      #
###################
networks:
  quackStack-network:
    driver: "bridge"
