# Common postgres vars
x-var:
  - &POSTGRES_USER
    postgres
  - &POSTGRES_PASSWORD
    default
  - &POSTGRES_DATABASE
    postgres

x-postgres-vars: &postgres-vars
  POSTGRES_HOST: quackStack-db
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

name: quackstack-nmp
services:
  ##########################################################
  #                      DB                                #
  ##########################################################
  database:
    container_name: quackStack-db
    environment:
      <<: *postgres-vars
    image: postgres:15
    ports: [5432:5432]
    volumes: [./database/db/entrypoint:/docker-entrypoint-initdb.d]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    networks:
      - quackStack-network

  ####################
  #     PGAdmin      #
  ####################
  pgadmin:
    container_name: quackStack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qs.com
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports: [5050:80]
    networks:
      - quackStack-network

  ###################
  #   Backend      #
  ###################
  backend:
    container_name: quackStack-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    # env_file:
    #   - path: ./backend/.env
        # required: false
    environment:
      <<: *postgres-vars
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /backend/src
          ignore:
            - node_modules
    healthcheck:
      test: curl localhost:3000/api/health | grep 'NMP API is healthy and ready!'
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      database:
        condition: service_healthy
    networks:
      - quackStack-network

  ##########################################################
  #                      FrontEnd                          #
  ##########################################################
  frontend:
    container_name: quackStack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=localhost:3000/api
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          ignore:
            - node_modules
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://${VITE_HOST:-localhost}:5173 || exit 1",
        ]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - quackStack-network

###################
#   Networks      #
###################
networks:
  quackStack-network:
    driver: "bridge"
volumes:
  postgres:
    name: quackStack-db-vol-postgres
