openapi: "3.1.0"
info: 
  title: NMP - QuackStack API
  version: "1.0.0"
servers:
  - url: http://OPENSHIFT.STATIC.URL:3000/api
    description: QS NMP API Server
security: []
paths: 
  /health:
    description: API Health
    get:
      summary: Health status
      operationId: checkHealth
      description: |
        If the API is healthy, respond to request
        with a healthy status message
      responses:
        "200":
          description: NMP API is healthy and ready
        "400":
          description: Bad Request
