name: .Deploys

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub environment; usually PR (omit), TEST or PROD
        required: false
        type: string
      tag: 
        description: Container tag; usually PR number or latest
        required: false
        type: string
        value: ${{ github.event.number }}
      target:
        description: Deployment target; usually PR number, test or prod
        required: false
        type: string
        value: ${{ github.event.number }}

jobs:
  database:
    name: Database
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Database
        uses: bcgov-nr/action-deployer-openshift@v2.3.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: database/openshift.deploy.yml
          overwrite: false
          parameters:
            -p TAG=${{ inputs.tag }} -p TARGET=${{ inputs.target }}

  backend:
    name: Backend
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Backend
        uses: bcgov-nr/action-deployer-openshift@v2.3.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: backend/openshift.deploy.yml
          overwrite: true
          parameters:
            -p TAG=${{ inputs.tag }} -p TARGET=${{ inputs.target }}
          verification_path: /api/health
          verification_retry_attempts: "5"
          verification_retry_seconds: "15"

  frontend:
    name: Frontend
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Frontend
        uses: bcgov-nr/action-deployer-openshift@v2.3.0
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: frontend/openshift.deploy.yml
          overwrite: trues
          parameters:
            -p TAG=${{ inputs.tag }} -p TARGET=${{ inputs.target }}
